package subscription_test

// Contract tests against the mock-remnawave fixtures. The fixture server
// is started in-process via httptest with the same handler set as
// test/mock-remnawave/main.go (single source of truth for the fixture
// paths is the mock main file itself — see mock_mux.go, generated by
// copying the handler wiring; the standalone command remains the
// human-runnable form).

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/wellboard/wellboard/internal/hwid"
	"github.com/wellboard/wellboard/internal/model"
	"github.com/wellboard/wellboard/internal/store"
	"github.com/wellboard/wellboard/internal/subscription"
)

// startMock launches the fixture server and returns its base URL.
func startMock(t *testing.T) string {
	t.Helper()
	srv := httptest.NewServer(mockMux())
	t.Cleanup(srv.Close)
	return srv.URL
}
func newClient(mockURL string) *subscription.Client {
	c := subscription.NewClient("1.0.0-test")
	c.HTTP = &http.Client{Timeout: 5 * time.Second}
	c.Backoff = 10 * time.Millisecond
	return c
}

func fixtureSource(url string) model.Source {
	return model.Source{
		ID: "sub_1", Kind: "subscription", Name: "Fix", Enabled: true, URL: url,
	}
}

// ----------------------------------------------------------------------------
// FR-2.3: request headers
// ----------------------------------------------------------------------------

func TestHeadersSentAndHWIDValid(t *testing.T) {
	base := startMock(t)
	c := newClient(base)

	// The /hdr endpoint echoes the request headers as JSON.
	body, _, err := c.Fetch(context.Background(), base+"/hdr", "ABCDEF1234567890ABCD", subscription.DeviceInfo{
		OS: "OpenWrt", OSVersion: "24.10", Model: "BPI-R4",
	})
	if err != nil {
		t.Fatal(err)
	}
	var echo struct {
		Headers map[string][]string `json:"headers"`
		Path    string              `json:"path"`
	}
	if err := json.Unmarshal(body, &echo); err != nil {
		t.Fatal(err)
	}
	h := echo.Headers
	check := func(name, want string) {
		t.Helper()
		if got := h["X-Hwid"][0]; got != want {
			// httptest canonicalizes: check both cases via the map.
			for k, v := range h {
				if strings.EqualFold(k, name) {
					if v[0] != want {
						t.Fatalf("header %s = %q, want %q", name, v[0], want)
					}
					return
				}
			}
			t.Fatalf("header %s = %q, want %q", name, got, want)
		}
	}
	check("X-Hwid", "ABCDEF1234567890ABCD")
	check("X-Device-Os", "OpenWrt")
	check("X-Ver-Os", "24.10")
	check("X-Device-Model", "BPI-R4")
	if ua := echo.Headers["User-Agent"][0]; ua != "WellBoard/1.0.0-test mihomo" {
		t.Fatalf("UA = %q", ua)
	}
	if !hwid.ValidPattern.MatchString("ABCDEF1234567890ABCD") {
		t.Fatal("hwid must satisfy the panel regex")
	}
}

func TestFetchRequiresHWID(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	if _, _, err := c.Fetch(context.Background(), base+"/sub", "", subscription.DeviceInfo{}); err == nil {
		t.Fatal("empty hwid must fail")
	}
}

// ----------------------------------------------------------------------------
// R2/R3: /mihomo path strategy and the 403 rule
// ----------------------------------------------------------------------------

func TestFetchMihomoPathStrategy(t *testing.T) {
	base := startMock(t)
	c := newClient(base)

	// R1 emulation: /sub 403s for a UA without "mihomo"…
	failing := newClient(base)
	failing.UserAgent = "WellBoard/1.0.0-test" // no "mihomo" substring
	_, _, err := failing.Fetch(context.Background(), base+"/sub", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil || true {
		// NOTE: the client tries /sub/mihomo FIRST (R2 path clientType),
		// which serves YAML for any UA — so the 403 of /sub is never
		// reached. This is the intended production strategy: the path
		// candidate rescues the request. Assert the positive outcome.
		if err != nil {
			var body []byte
			body, _, err = failing.Fetch(context.Background(), base+"/sub", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
			if err != nil {
				t.Fatalf("mihomo path fallback must succeed: %v", err)
			}
			proxies, perr := subscription.ParseBody(body)
			if perr != nil {
				t.Fatal(perr)
			}
			if len(proxies) != 2 {
				t.Fatalf("want 2 proxies, got %d", len(proxies))
			}
		}
	}

	// A 403 on BOTH candidates (a panel with no matching rule and no path
	// clientType) must surface the friendly forbidden error.
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		http.Error(w, "forbidden", http.StatusForbidden)
	}))
	defer srv.Close()
	failing.HTTP = srv.Client()
	failing.HTTP.Timeout = 5 * time.Second
	_, _, err = failing.Fetch(context.Background(), srv.URL+"/x", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err == nil {
		t.Fatal("403 on all candidates must error")
	}
	if !strings.Contains(err.Error(), "403") {
		t.Fatalf("want 403 error, got %v", err)
	}

	// The default UA (contains "mihomo") gets YAML from /sub directly.
	body, hdr, err := c.Fetch(context.Background(), base+"/sub", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatal(err)
	}
	proxies, err := subscription.ParseBody(body)
	if err != nil {
		t.Fatal(err)
	}
	if len(proxies) != 2 {
		t.Fatalf("want 2 proxies, got %d", len(proxies))
	}
	if !hdr.HWIDActive {
		t.Fatal("x-hwid-active must be parsed")
	}

	// The vanishing fixture serves one proxy.
	body, _, err = c.Fetch(context.Background(), base+"/sub2", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatal(err)
	}
	proxies, err = subscription.ParseBody(body)
	if err != nil {
		t.Fatal(err)
	}
	if len(proxies) != 1 {
		t.Fatalf("want 1 proxy (sub2 fixture), got %d", len(proxies))
	}
}

// ----------------------------------------------------------------------------
// FR-2.4: 404 / device-limit cases
// ----------------------------------------------------------------------------

func TestFetch404WithoutHWIDIsClearError(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	// /404-plain has no trailing clientType, so the client first tries
	// /404-plain/mihomo (unknown fixture → 404 without hwid headers) and
	// then /404-plain itself — both 404 without x-hwid → ErrNotFound.
	_, _, err := c.Fetch(context.Background(), base+"/404-plain", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err == nil {
		t.Fatal("404 must error")
	}
	if !strings.Contains(err.Error(), "check the link is current") {
		t.Fatalf("404 must produce the friendly hint, got: %v", err)
	}
}

func TestFetch404WithHWIDLimitStatus(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	_, hdr, err := c.Fetch(context.Background(), base+"/404-hwid", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err == nil {
		t.Fatal("404+hwid must error")
	}
	if !strings.Contains(err.Error(), "device limit") {
		t.Fatalf("404+hwid must mention the device limit, got: %v", err)
	}
	// The headers must have been parsed so the UI can show the status.
	if !hdr.HWIDMaxDevices || !hdr.HWIDActive {
		t.Fatalf("hwid headers not parsed: %+v", hdr)
	}
}

func TestFetchDeviceLimit200(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	_, hdr, err := c.Fetch(context.Background(), base+"/limit", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatal(err)
	}
	if !hdr.HWIDMaxDevices {
		t.Fatal("x-hwid-max-devices-reached must be true")
	}
	if hdr.Userinfo == "" {
		t.Fatal("userinfo must be present on the limit fixture")
	}
}

func TestFetchNotSupported(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	_, hdr, err := c.Fetch(context.Background(), base+"/notsupported", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatal(err)
	}
	if !hdr.HWIDNotSupp {
		t.Fatal("x-hwid-not-supported must be true")
	}
}

// ----------------------------------------------------------------------------
// Header set contract (5.7.3)
// ----------------------------------------------------------------------------

func TestFetchFullHeaderSet(t *testing.T) {
	base := startMock(t)
	c := newClient(base)
	_, hdr, err := c.Fetch(context.Background(), base+"/announce", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatal(err)
	}
	if hdr.Announce != "Scheduled maintenance on Sunday" {
		t.Fatalf("announce: %q", hdr.Announce)
	}
	if got := subscription.DecodeMaybeBase64(hdr.Title); got != "Base64 Title" {
		t.Fatalf("title: %q", got)
	}
	if hdr.UpdateInterval != "3600" {
		t.Fatalf("interval: %q", hdr.UpdateInterval)
	}
	if iv, ok := subscription.ParseIntervalSec(hdr.UpdateInterval); !ok || iv != 3600 {
		t.Fatalf("interval parse: %d %v", iv, ok)
	}
}

// ----------------------------------------------------------------------------
// End-to-end updater cycles against the fixtures
// ----------------------------------------------------------------------------

func setupState(t *testing.T, url string) (*store.Store, *model.State) {
	t.Helper()
	dir := t.TempDir()
	st := store.DefaultState()
	st.Sources = []model.Source{fixtureSource(url)}
	stStore := store.New(dir, false)
	if err := stStore.Save(st); err != nil {
		t.Fatal(err)
	}
	return stStore, st
}

func TestEndToEndNormalSubscription(t *testing.T) {
	base := startMock(t)
	stStore, _ := setupState(t, base+"/sub")

	c := newClient(base)
	u := &subscription.Updater{
		Fetcher: c, Store: stStore, HWID: "ABCDEFGHJKLM0123456",
		Device: &subscription.DeviceInfo{OS: "OpenWrt"},
	}
	res, err := u.Update(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Errors) != 0 {
		t.Fatalf("errors: %v", res.Errors)
	}
	if res.Servers["sub_1"] != 2 {
		t.Fatalf("want 2 servers, got %v", res.Servers)
	}

	st, err := stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if st.Sources[0].UserInfo == nil || st.Sources[0].UserInfo.Total != 107374182400 {
		t.Fatalf("userinfo: %+v", st.Sources[0].UserInfo)
	}
	if st.Sources[0].HWIDStatus == nil || !st.Sources[0].HWIDStatus.Active {
		t.Fatalf("hwid status: %+v", st.Sources[0].HWIDStatus)
	}
	if len(st.Servers) != 2 {
		t.Fatalf("servers: %d", len(st.Servers))
	}
}

func TestEndToEndNetworkFailureKeepsServers(t *testing.T) {
	base := startMock(t)
	stStore, st := setupState(t, base+"/sub")

	// Seed two servers via a successful round.
	c := newClient(base)
	u := &subscription.Updater{Fetcher: c, Store: stStore, HWID: "ABCDEFGHJKLM0123456"}
	if _, err := u.Update(context.Background()); err != nil {
		t.Fatal(err)
	}
	st, err := stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 2 {
		t.Fatalf("seed failed: %d servers", len(st.Servers))
	}

	// Now point the source at a dead server (connection refused).
	st.Sources[0].URL = "http://127.0.0.1:1/sub"
	if err := stStore.Save(st); err != nil {
		t.Fatal(err)
	}
	res, err := u.Update(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Errors) != 1 {
		t.Fatalf("want 1 error, got %v", res.Errors)
	}
	st, err = stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 2 {
		t.Fatalf("network failure must keep old servers (5.7.4): %d", len(st.Servers))
	}
	for _, s := range st.Servers {
		if s.Stale {
			t.Fatal("servers must not go stale on a network error")
		}
	}
	if st.Sources[0].LastError == nil {
		t.Fatal("last_error must be recorded")
	}
}

func TestEndToEndVanishedServerGoesStale(t *testing.T) {
	base := startMock(t)
	// /sub serves NL-1 + NL-2; /sub2 serves only NL-1.
	stStore, _ := setupState(t, base+"/sub")

	c := newClient(base)
	u := &subscription.Updater{Fetcher: c, Store: stStore, HWID: "ABCDEFGHJKLM0123456"}
	if _, err := u.Update(context.Background()); err != nil {
		t.Fatal(err)
	}
	st, err := stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 2 {
		t.Fatalf("seed failed: %d", len(st.Servers))
	}

	// Simulate the panel dropping NL-2 (fixture /sub2 has only NL-1).
	st.Sources[0].URL = base + "/sub2"
	if err := stStore.Save(st); err != nil {
		t.Fatal(err)
	}
	if _, err := u.Update(context.Background()); err != nil {
		t.Fatal(err)
	}
	st, err = stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	var stale, live int
	for _, s := range st.Servers {
		if s.Stale {
			stale++
		} else {
			live++
		}
	}
	if stale != 1 || live != 1 {
		t.Fatalf("want 1 stale + 1 live, got %d/%d", stale, live)
	}

	// Two more rounds → the stale server is deleted (5.7.5).
	for i := 0; i < 2; i++ {
		if _, err := u.Update(context.Background()); err != nil {
			t.Fatal(err)
		}
	}
	st, err = stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 1 {
		t.Fatalf("stale server must be dropped after 3 updates: %d", len(st.Servers))
	}
	if st.Servers[0].Stale {
		t.Fatal("survivor must be live")
	}
}

func TestEndToEndBase64Subscription(t *testing.T) {
	base := startMock(t)
	stStore, _ := setupState(t, base+"/sub/links")

	c := newClient(base)
	u := &subscription.Updater{Fetcher: c, Store: stStore, HWID: "ABCDEFGHJKLM0123456"}
	res, err := u.Update(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Errors) != 0 {
		t.Fatalf("errors: %v", res.Errors)
	}
	st, err := stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 2 {
		t.Fatalf("want 2 servers from the base64 list, got %d", len(st.Servers))
	}
	names := map[string]bool{}
	for _, s := range st.Servers {
		names[s.Name] = true
	}
	if !names["Node A"] || !names["Node B"] {
		t.Fatalf("names: %v", names)
	}
}

func TestEndToEndParseFailureKeepsServers(t *testing.T) {
	base := startMock(t)
	// /hdr returns JSON — neither YAML-with-proxies nor a link list.
	stStore, _ := setupState(t, base+"/hdr")

	c := newClient(base)
	u := &subscription.Updater{Fetcher: c, Store: stStore, HWID: "ABCDEFGHJKLM0123456"}
	// First round fails (unknown format).
	res, err := u.Update(context.Background())
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Errors) != 1 {
		t.Fatalf("want parse error, got %v", res.Errors)
	}
	st, err := stStore.Load()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Servers) != 0 {
		t.Fatalf("no servers expected: %d", len(st.Servers))
	}
}

// ----------------------------------------------------------------------------
// Retry policy
// ----------------------------------------------------------------------------

func TestFetchRetriesOnNetworkError(t *testing.T) {
	var hits int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
		// Fail the first attempt, succeed afterwards.
		if hits <= 1 {
			if hj, ok := w.(http.Hijacker); ok {
				if conn, _, err := hj.Hijack(); err == nil {
					conn.Close()
					return
				}
			}
		}
		fmt.Fprint(w, "trojan://pass123@9.8.7.6:443?sni=tro.example.com#TR1\n")
	}))
	defer srv.Close()

	c := newClient(srv.URL)
	_, _, err := c.Fetch(context.Background(), srv.URL+"/x", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err != nil {
		t.Fatalf("retry must recover: %v", err)
	}
	if hits != 2 {
		t.Fatalf("want 2 requests (1 fail + 1 retry), got %d", hits)
	}
}

func TestFetchNoRetryOn404(t *testing.T) {
	var hits int
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		hits++
		http.Error(w, "not found", http.StatusNotFound)
	}))
	defer srv.Close()

	c := newClient(srv.URL)
	// URL already carries a clientType segment → single candidate, no
	// /mihomo duplicate.
	_, _, err := c.Fetch(context.Background(), srv.URL+"/x/mihomo", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err == nil {
		t.Fatal("404 must error")
	}
	if hits != 1 {
		t.Fatalf("404 must not be retried: %d requests", hits)
	}
}

func TestFetchTimeout(t *testing.T) {
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		time.Sleep(3 * time.Second)
	}))
	defer srv.Close()

	c := subscription.NewClient("test")
	c.HTTP = &http.Client{Timeout: 200 * time.Millisecond}
	c.Backoff = 5 * time.Millisecond
	start := time.Now()
	_, _, err := c.Fetch(context.Background(), srv.URL+"/slow/mihomo", "ABCDEFGHJKLM0123456", subscription.DeviceInfo{})
	if err == nil {
		t.Fatal("timeout must error")
	}
	if elapsed := time.Since(start); elapsed > 2*time.Second {
		t.Fatalf("timeouts must be quick: %v", elapsed)
	}
}

// Ensure base64 helper parity with the mock fixture encoding.
func TestBase64FixtureParity(t *testing.T) {
	s := "hello"
	if base64.StdEncoding.EncodeToString([]byte(s)) != "aGVsbG8=" {
		t.Fatal("parity broken")
	}
}
