// Package generator converts WellBoard state into a mihomo profile YAML
// (initial TZ 5.4). The output is deterministic and covered by golden tests
// (test/golden/).
//
// Generated sections, in order:
//
//	proxies        — every enabled, non-stale server from every enabled
//	                 source; name "<display> [<source>]", collisions get
//	                 " #2"… (initial TZ 5.4.1)
//	proxy-groups   — user groups as defined; one service "rt:<id>" fallback
//	                 group per enabled route (target, then REJECT|DIRECT per
//	                 on_unavailable, decision Q4 / FR-4.7); "rt:default"
//	                 select group for the default policy (FR-4.6).
//	rule-providers — emitted when geosite conditions exist OR any route
//	                 references local fallback providers (FR-5.4, Phase 3):
//	                 one "type: file, behavior: domain" entry per provider,
//	                 path "./providers/<name>.yaml"; the caller materializes
//	                 the payload files next to the profile (WriteProviders).
//	rules          — one line per condition per route, in ascending route
//	                 order (FR-4.5), plus one RULE-SET line per referenced
//	                 provider; the last line is MATCH,rt:default.
//
// Transport sections (tun, dns, ports, external-controller, …) are NOT
// generated: they belong to nikki (docs/DECISIONS.md N3).
//
// Referential integrity is enforced loudly: a route whose target server or
// group no longer exists (FR-4.8), or other broken references, abort
// generation with a *Problems error — never a silently degraded profile.
package generator

import (
	"fmt"
	"math"
	"sort"
	"strings"

	"github.com/wellboard/wellboard/internal/model"
	"gopkg.in/yaml.v3"
)

// Header comment written on top of every generated profile (Appendix A).
const Header = "# generated by WellBoard v1 — do not edit by hand"

// HealthCheckURL is the mihomo group health-check target (initial TZ,
// Appendix A example).
const HealthCheckURL = "https://www.gstatic.com/generate_204"

// ServiceGroupPrefix marks WellBoard service groups in the generated
// profile: "rt:<route-id>" per route, plus "rt:default" for the MATCH
// policy. User groups must not use this prefix.
const (
	ServiceGroupPrefix = "rt:"
	DefaultGroupName   = "rt:default"
)

// RouteGroupIntervalSec is the health-check interval of per-route service
// fallback groups (Appendix A: interval 60).
const RouteGroupIntervalSec = 60

// UserGroupURLTestIntervalSec is the url-test interval for user groups when
// settings.delay_test_interval_sec is unset; matches the initial TZ example
// (Appendix A: interval 300, settings default 300).
const UserGroupURLTestIntervalSec = 300

// UserGroupTolerance is the url-test tolerance for user groups
// (Appendix A: tolerance 50).
const UserGroupTolerance = 50

// Problems is the structured validation report returned (as an error) when
// the state cannot be translated into a safe profile. The caller surfaces
// it to the user (FR-4.8: "target lost" — never apply silently).
type Problems struct {
	// LostTargets holds "route <id>: target …" entries for routes whose
	// target server/group is missing, disabled or stale.
	LostTargets []string
	// Invalid holds other per-object rejections with context.
	Invalid []string
}

// Error implements error with a human-readable, line-per-problem report.
func (p *Problems) Error() string {
	var b strings.Builder
	b.WriteString("wellboard: profile generation failed:")
	for _, m := range p.LostTargets {
		fmt.Fprintf(&b, "\n  route %s: target lost", m)
	}
	for _, m := range p.Invalid {
		fmt.Fprintf(&b, "\n  %s", m)
	}
	return b.String()
}

func (p *Problems) add(format string, args ...any) {
	p.Invalid = append(p.Invalid, fmt.Sprintf(format, args...))
}

func (p *Problems) lost(routeID, detail string) {
	p.LostTargets = append(p.LostTargets, fmt.Sprintf("%s (%s)", routeID, detail))
}

func (p *Problems) empty() bool {
	return len(p.LostTargets) == 0 && len(p.Invalid) == 0
}

// profile is the generated mihomo document. RuleProviders is a pointer so
// the section can be emitted as an explicit empty mapping when geodata is
// in play (yaml.v3 omitempty drops both nil and empty maps).
type profile struct {
	Proxies       []map[string]any `yaml:"proxies"`
	ProxyGroups   []map[string]any `yaml:"proxy-groups"`
	RuleProviders *map[string]any  `yaml:"rule-providers,omitempty"`
	Rules         []string         `yaml:"rules"`
}

// Generate translates st into a mihomo profile YAML document. It returns
// the rendered bytes; a *Problems error means the state references objects
// that no longer exist and must be surfaced to the user (FR-4.8).
func Generate(st *model.State) (out []byte, err error) {
	return GenerateWithProviders(st, nil)
}

// GenerateWithProviders additionally knows the set of provider names
// that have a local payload file (FR-5.4). A route referencing a provider
// without a payload is a Problems entry (the profile would point at a
// missing file). Names not in known but referenced by routes are still
// emitted; known may be nil (skip the existence check — dev mode /
// caller-provided providers).
func GenerateWithProviders(st *model.State, known map[string]bool) (out []byte, err error) {
	if st == nil {
		return nil, fmt.Errorf("generator: nil state")
	}
	doc, err := build(st)
	if err != nil {
		return nil, err
	}
	if known != nil {
		var missing []string
		if rp := doc.RuleProviders; rp != nil {
			for name := range *rp {
				if !known[name] {
					missing = append(missing, name)
				}
			}
		}
		if len(missing) > 0 {
			sort.Strings(missing)
			// Reported as *Problems (not a plain error) so the API maps
			// it to 409 with the offending provider names (FR-5.4
			// referential conflict, same class as lost targets).
			return nil, &Problems{Invalid: []string{fmt.Sprintf(
				"no local payload for provider(s) %v (routes referencing them must be fixed or the provider shipped)", missing)}}
		}
	}
	out, err = marshalProfile(doc)
	if err != nil {
		return nil, err
	}
	var b strings.Builder
	b.WriteString(Header)
	b.WriteString("\n")
	b.Write(out)
	return []byte(b.String()), nil
}

// marshalProfile renders the document. yaml.v3 PANICS (it does not return
// an error) when it meets a value it cannot encode — e.g. a channel or
// function smuggled into a server Raw map. Recover here so a corrupt state
// yields an error instead of crashing the daemon.
func marshalProfile(doc *profile) (out []byte, err error) {
	defer func() {
		if r := recover(); r != nil {
			out = nil
			err = fmt.Errorf("generator: marshal profile: unsupported value in state: %v", r)
		}
	}()
	out, err = yaml.Marshal(doc)
	if err != nil {
		err = fmt.Errorf("generator: marshal profile: %w", err)
	}
	return out, err
}

// build assembles the profile document from state.
func build(st *model.State) (*profile, error) {
	prob := &Problems{}

	// Enabled sources: manual buckets are always live; subscriptions only
	// when enabled. Source display names feed the proxy naming scheme.
	srcEnabled := map[string]bool{}
	srcName := map[string]string{}
	for _, src := range st.Sources {
		if src.Kind == string(model.SourceManual) || src.Enabled {
			srcEnabled[src.ID] = true
			srcName[src.ID] = src.Name
		}
	}

	// --- 1. proxies -------------------------------------------------
	// Namespace shared by proxies and groups: mihomo requires unique names
	// across both, so collisions are resolved globally with " #2", " #3"…
	usedNames := map[string]int{}

	proxies := make([]map[string]any, 0, len(st.Servers))
	nameByID := map[string]string{} // server ID → mihomo proxy name
	for _, srv := range st.Servers {
		if !srcEnabled[srv.SourceID] || srv.Stale {
			continue // not part of the active pool
		}
		if len(srv.Raw) == 0 {
			prob.add("server %s: empty raw proxy map, skipped", srv.ID)
			continue
		}
		display := uniqueName(fmt.Sprintf("%s [%s]", srv.Name, srcName[srv.SourceID]), usedNames)
		nameByID[srv.ID] = display

		entry := map[string]any{}
		for k, v := range srv.Raw {
			entry[k] = normalize(v)
		}
		entry["name"] = display
		proxies = append(proxies, entry)
	}

	// --- 2a. user groups: assign names first, resolve members after ---
	// Two passes so group members may reference groups defined later in
	// the state (mihomo allows forward references between groups).
	groupsByID := map[string]model.Group{}
	for _, g := range st.Groups {
		groupsByID[g.ID] = g
	}
	groupNameByID := map[string]string{} // group ID → mihomo group name
	for _, g := range st.Groups {
		if strings.HasPrefix(g.Name, ServiceGroupPrefix) {
			prob.add("group %s: name %q uses reserved prefix %q", g.ID, g.Name, ServiceGroupPrefix)
		}
		groupNameByID[g.ID] = uniqueName(g.Name, usedNames)
	}

	userGroups := make([]map[string]any, 0, len(st.Groups))
	for _, g := range st.Groups {
		gname := groupNameByID[g.ID]

		members := make([]string, 0, len(g.Members))
		for _, m := range g.Members {
			switch {
			case m == g.ID:
				prob.add("group %s: self-reference skipped", g.ID)
			case nameByID[m] != "":
				members = append(members, nameByID[m])
			case groupNameByID[m] != "":
				members = append(members, groupNameByID[m])
			default:
				// Missing member: report, never silently drop the whole
				// group (FR-4.8 spirit).
				prob.add("group %s: member %s not found, skipped", g.ID, m)
			}
		}
		if len(members) == 0 {
			// An empty proxies list would fail mihomo config parsing.
			members = []string{"DIRECT"}
			prob.add("group %s: no resolvable members, substituted DIRECT", g.ID)
		}

		grp := map[string]any{
			"name":    gname,
			"type":    string(g.Type),
			"proxies": members,
		}
		switch g.Type {
		case model.GroupURLTest:
			grp["url"] = HealthCheckURL
			grp["interval"] = groupInterval(st)
			grp["tolerance"] = UserGroupTolerance
		case model.GroupFallback, model.GroupLoadBalance:
			grp["url"] = HealthCheckURL
			grp["interval"] = groupInterval(st)
		case model.GroupSelect:
			// No health check for manual selection.
		default:
			prob.add("group %s: unknown type %q", g.ID, g.Type)
		}
		userGroups = append(userGroups, grp)
	}

	// --- 2b. service groups + rules ----------------------------------
	// Routes in ascending order; ties broken by ID for determinism
	// (FR-4.5: user order translates 1:1 into rules order).
	routes := append([]model.Route(nil), st.Routes...)
	sort.SliceStable(routes, func(i, j int) bool {
		if routes[i].Order != routes[j].Order {
			return routes[i].Order < routes[j].Order
		}
		return routes[i].ID < routes[j].ID
	})

	// resolveTarget returns the mihomo entity name for a route/default
	// target plus existence. Only active-pool entities exist.
	resolveTarget := func(t model.Target) (string, bool) {
		switch t.Type {
		case model.TargetDirect:
			return "DIRECT", true
		case model.TargetReject:
			return "REJECT", true
		case model.TargetServer:
			if n, ok := nameByID[t.ID]; ok {
				return n, true
			}
			return "", false
		case model.TargetGroup:
			if n, ok := groupNameByID[t.ID]; ok {
				return n, true
			}
			return "", false
		}
		return "", false
	}

	serviceGroups := make([]map[string]any, 0, len(routes)+1)
	rules := make([]string, 0, 8)
	needGeosite := false
	usedProviders := map[string]bool{}

	for _, rt := range routes {
		if !rt.Enabled {
			continue // user-disabled route: skip silently
		}
		target, ok := resolveTarget(rt.Target)
		if !ok {
			prob.lost(rt.ID, targetDetail(rt.Target, groupsByID))
			continue
		}

		// Service fallback group: [target, REJECT|DIRECT]. When the target
		// itself is REJECT/DIRECT the fail-over member is redundant and the
		// group degrades to the single target.
		failover := "REJECT" // decision Q4: block by default
		if rt.OnUnavailable == "direct" {
			failover = "DIRECT"
		}
		members := []string{target}
		if failover != target {
			members = append(members, failover)
		}
		svcName := ServiceGroupPrefix + rt.ID
		serviceGroups = append(serviceGroups, map[string]any{
			"name":     svcName,
			"type":     "fallback",
			"proxies":  members,
			"url":      HealthCheckURL,
			"interval": RouteGroupIntervalSec,
		})

		if len(rt.Conditions) == 0 && len(rt.Providers) == 0 {
			prob.add("route %s: no conditions, no rules emitted", rt.ID)
			continue
		}
		for _, c := range rt.Conditions {
			line, isGeo, err := conditionRule(c)
			if err != nil {
				prob.add("route %s: %v", rt.ID, err)
				continue
			}
			if isGeo {
				needGeosite = true
			}
			rules = append(rules, line+","+svcName)
		}
		// Local fallback providers (FR-5.4): one RULE-SET line each,
		// AFTER the explicit conditions of the same route (same target).
		for _, p := range rt.Providers {
			if err := validProviderName(p); err != nil {
				prob.add("route %s: provider %q: %v", rt.ID, p, err)
				continue
			}
			if usedProviders[p] {
				prob.add("route %s: provider %q already used by an earlier route", rt.ID, p)
				continue
			}
			usedProviders[p] = true
			rules = append(rules, "RULE-SET,"+p+","+svcName)
		}
	}

	// rt:default for the MATCH policy (decision Q3, FR-4.6, Appendix A).
	dp, ok := resolveTarget(st.Settings.DefaultPolicy)
	if !ok {
		prob.add("settings.default_policy: target %q not found, using DIRECT",
			st.Settings.DefaultPolicy.ID)
		dp = "DIRECT"
	}
	serviceGroups = append(serviceGroups, map[string]any{
		"name":    DefaultGroupName,
		"type":    "select",
		"proxies": []string{dp},
	})
	rules = append(rules, "MATCH,"+DefaultGroupName)

	if !prob.empty() {
		return nil, prob
	}

	prof := &profile{
		Proxies:     proxies,
		ProxyGroups: append(userGroups, serviceGroups...),
		Rules:       rules,
	}
	if needGeosite || len(usedProviders) > 0 {
		rp := map[string]any{}
		// Stable order: sorted provider names.
		for _, p := range sortedKeys(usedProviders) {
			rp[p] = map[string]any{
				"type":     "file",
				"behavior": "domain",
				"path":     ProviderPath(p),
			}
		}
		prof.RuleProviders = &rp
	}
	return prof, nil
}

// ProviderPath is the rule-provider payload path written into the
// profile: "./providers/<name>.yaml" (relative to the profile file, the
// same convention nikki uses for its run dir).
func ProviderPath(name string) string {
	return "./providers/" + name + ".yaml"
}

// validProviderName guards the rule-provider names that end up in the
// profile (path safety: [a-zA-Z0-9-] only).
func validProviderName(p string) error {
	if p == "" {
		return fmt.Errorf("empty provider name")
	}
	for _, r := range p {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-':
		default:
			return fmt.Errorf("only [a-zA-Z0-9-] allowed")
		}
	}
	return nil
}

func sortedKeys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// targetDetail explains why a target did not resolve (for the Problems
// report).
func targetDetail(t model.Target, groupsByID map[string]model.Group) string {
	switch t.Type {
	case model.TargetServer:
		return fmt.Sprintf("server %s not found, disabled or stale", t.ID)
	case model.TargetGroup:
		if g, ok := groupsByID[t.ID]; ok {
			return fmt.Sprintf("group %s (%s) not usable", t.ID, g.Name)
		}
		return fmt.Sprintf("group %s not found", t.ID)
	}
	return fmt.Sprintf("unresolvable target type %q", t.Type)
}

// groupInterval picks the health-check interval for user groups: the
// settings value, else the Appendix A default (300).
func groupInterval(st *model.State) int {
	if st.Settings.DelayTestIntervalSec > 0 {
		return st.Settings.DelayTestIntervalSec
	}
	return UserGroupURLTestIntervalSec
}

// uniqueName appends " #2", " #3"… when the same display name was already
// used by a proxy or group (initial TZ 5.4.1).
func uniqueName(display string, used map[string]int) string {
	n := used[display]
	used[display] = n + 1
	if n == 0 {
		return display
	}
	return fmt.Sprintf("%s #%d", display, n+1)
}

// conditionRule renders one condition as the mihomo rule prefix (the route
// service group is appended by the caller). isGeo reports whether the rule
// needs geodata (GEOSITE).
func conditionRule(c model.RouteCondition) (line string, isGeo bool, err error) {
	// Rule-line safety (security audit Phase 7): condition values are
	// rendered into comma-separated mihomo rule lines; ',', ':' or
	// newlines would inject spurious rule segments / profile structure.
	// The API validates this at write time too — the generator check
	// covers states that arrived via import or hand-edited state.json.
	if strings.ContainsAny(c.Value, ",:\n\r") {
		return "", false, fmt.Errorf("condition %s value %q must not contain ',', ':' or newlines", c.Type, c.Value)
	}
	switch c.Type {
	case model.CondDomain:
		return "DOMAIN," + c.Value, false, nil
	case model.CondDomainSuffix:
		return "DOMAIN-SUFFIX," + c.Value, false, nil
	case model.CondDomainKeyword:
		return "DOMAIN-KEYWORD," + c.Value, false, nil
	case model.CondGeosite:
		if c.Value == "" {
			return "", false, fmt.Errorf("geosite condition without category")
		}
		return "GEOSITE," + c.Value, true, nil
	case model.CondGeoIP:
		return "GEOIP," + c.Value, false, nil
	case model.CondIPCIDR:
		return "IP-CIDR," + c.Value, false, nil
	case model.CondSrcDevice:
		// The value is the LAN device IP in CIDR form (FR-4.4: mihomo
		// matches by IP, not MAC).
		if c.Value == "" {
			return "", false, fmt.Errorf("src-device condition without ip")
		}
		return "SRC-IP-CIDR," + c.Value, false, nil
	case model.CondDstPort:
		return "DST-PORT," + c.Value, false, nil
	}
	return "", false, fmt.Errorf("unknown condition type %q", c.Type)
}

// normalize converts JSON-decoded numbers (float64) with integral values
// to int so YAML renders `port: 443`, never `443.0` or `4.43e+02`
// (state.json round-trips through encoding/json). Maps and lists are
// normalized recursively.
func normalize(v any) any {
	switch t := v.(type) {
	case float64:
		if t == math.Trunc(t) && !math.IsInf(t, 0) && math.Abs(t) < 1e15 {
			return int64(t)
		}
		return t
	case map[string]any:
		out := make(map[string]any, len(t))
		for k, vv := range t {
			out[k] = normalize(vv)
		}
		return out
	case []any:
		out := make([]any, len(t))
		for i, vv := range t {
			out[i] = normalize(vv)
		}
		return out
	default:
		return v
	}
}
